#CI_COMMIT_MESSAGE => commit
#CI_COMMIT_REF_NAME => branch
#CI_PIPELINE_IID => id de la pipeline
#chmod +x env/bin/activate
#./env/bin/activate
#python3.7 ...

variables:
        MYSQL_DATABASE: "earlynews_test"
        MYSQL_ROOT_PASSWORD: "admin"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        PROJECT_NAME: "Backend"

test_backend:
    stage: test
    
    artifacts:
        paths: 
            - Easy_News
        expire_in: 1 week
    
    services:
        - name: mariadb:latest
    
    image: faltren/dotnet-sdk-npm-3:pip3
    before_script:
        - chmod +x /env/bin/activate
        - /env/bin/activate
        - python3.7 Easy_News/Discord/notify.py 'ci' "----------------------------------------------\n |             NEW PIPELINE STARTED            | \n |Starting backend CI for the commit         |\n|    $CI_COMMIT_TITLE \n |in pipeline number   $CI_PIPELINE_IID                            |\n----------------------------------------------"
        
    script:
        - cd Easy_News
        - cd $PROJECT_NAME
        - dotnet restore
        - dotnet build $PROJECT_NAME.sln
        - dotnet test Tests