variables:
        MYSQL_DATABASE: "earlynews_test"
        MYSQL_ROOT_PASSWORD: "admin"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        PROJECT_NAME: "Backend"

merge:
    image: faltren/dotnet-sdk-npm-3:python

    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == 'master'
    
    script:
        - echo MERGED

test_backend:
    stage: test
    
    artifacts:
        paths: 
            - Easy_News
        expire_in: 1 week
    
    services:
        - name: mariadb:latest
    
    image: faltren/dotnet-sdk-npm-3:python
    before_script:
        - cd Easy_News
        - cd $PROJECT_NAME
        - dotnet restore
        - dotnet build $PROJECT_NAME.sln
    script:
        - dotnet test Tests

test_website:
    stage: test
    
    artifacts:
        paths: 
            - Easy_News
        expire_in: 1 week

    services:
        - name: mariadb:latest
    
    image: faltren/dotnet-sdk-npm-3:python
    before_script:
        - cd Easy_News
        - cd $PROJECT_NAME
        - dotnet restore
        - dotnet build $PROJECT_NAME.sln
    script:
        - dotnet test Tests
        - nohup dotnet run --project Backend/Backend.csproj > /dev/null 2>&1 &
        - cd ../site; 
        - npm install
        - npm test