#CI_COMMIT_MESSAGE => commit
#CI_COMMIT_REF_NAME => branch
#CI_PIPELINE_IID => id de la pipeline
#chmod +x env/bin/activate
#./env/bin/activate
#python3.7 ...

variables:
        MYSQL_DATABASE: "earlynews_test"
        MYSQL_ROOT_PASSWORD: "admin"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        PROJECT_NAME: "Backend"

merge:
    image: faltren/dotnet-sdk-npm-3:python

    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == 'master'
    
    script:
        - chmod +x /env/bin/activate
        - /env/bin/activate
        - python3.7 Easy_News/Discord/notify.py 'ci' "NEW MERGE \n Merging $CI_COMMIT_REF_NAME"
        - /env/bin/deactivate

test_backend:
    stage: test
    
    artifacts:
        paths: 
            - Easy_News
        expire_in: 1 week
    
    services:
        - name: mariadb:latest
    
    image: faltren/dotnet-sdk-npm-3:pip3
    before_script:
        - chmod +x /env/bin/activate
        - /env/bin/activate
        - python3.7 Easy_News/Discord/notify.py 'ci' "NEW PIPELINE STARTED \n Starting backend CI for the commit\n    $CI_COMMIT_TITLE \n \n in pipeline number   $CI_PIPELINE_IID"
        
    script:
        - cd Easy_News
        - cd $PROJECT_NAME
        - dotnet restore
        - dotnet build $PROJECT_NAME.sln
        - dotnet test Tests

test_website:
    stage: test
    
    artifacts:
        paths: 
            - Easy_News
        expire_in: 1 week

    services:
        - name: mariadb:latest
    
    image: faltren/dotnet-sdk-npm-3:pip3
    
    before_script:
        - chmod +x /env/bin/activate
        - /env/bin/activate
        - python3.7 Easy_News/Discord/notify.py 'ci' "NEW PIPELINE STARTED \n Starting website CI for the commit\n    $CI_COMMIT_TITLE \n \n in pipeline number   $CI_PIPELINE_IID"
        
    script:
        - cd Easy_News
        - cd $PROJECT_NAME
        - dotnet restore
        - dotnet build $PROJECT_NAME.sln
        - dotnet test Tests
        - nohup dotnet run --project Backend/Backend.csproj > /dev/null 2>&1 &
        - cd ../site; 
        - npm install
        - npm test
        
on_failure:
    image: faltren/dotnet-sdk-npm-3:pip3

    stage: .post
    when: on_failure
    
    script:
        - chmod +x /env/bin/activate
        - /env/bin/activate
        - python3.7 Easy_News/Discord/notify.py 'ci' "PIPELINE FAILED \n pipeline number   $CI_PIPELINE_IID"
        
on_success: 
    image: faltren/dotnet-sdk-npm-3:pip3

    stage: .post
    when: on_success
    
    script:
        - chmod +x /env/bin/activate
        - /env/bin/activate
        - python3.7 Easy_News/Discord/notify.py 'ci' "PIPELINE SUCCESS \n pipeline number   $CI_PIPELINE_IID"