stages:
    - build-project
  
variables:
        MYSQL_DATABASE: "earlynews_test"
        MYSQL_ROOT_PASSWORD: "admin"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        PROJECT_NAME: "Backend"

build-project:
    stage: build-project

    services:
        - name: mariadb:latest
          #command: ["/usr/bin/mysql", "--user=root", "--password=$MYSQL_ROOT_PASSWORD", "--host=mariadb", "$MYSQL_DATABASE < Early_News/SQL/InitTableTest.sql"]
    
    
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    before_script:
        - apt-get update -y
        - apt-get install -yq nodejs npm
        - cd Easy_News
        - cd $PROJECT_NAME
        - dotnet restore
        - dotnet build $PROJECT_NAME.sln
    script:
        - dotnet test Tests
        - nohup dotnet run --project Backend/Backend.csproj > /dev/null 2>&1 &
        - cd ../site; 
        - npm install
        - npm test