CREATE TABLE `Test_values` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Value` INT(11) NULL DEFAULT NULL,
	`Text` LONGTEXT NULL,
	`Boolean` TINYINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);